# Generated by Django 2.2.3 on 2019-08-18 02:46

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=110, verbose_name='descripción')),
                ('imagen', models.ImageField(upload_to=apps.blog.models.custom_upload_to, verbose_name='Imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo/Inactivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacíon')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
