# Generated by Django 2.2.3 on 2019-08-18 21:45

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.custom_autor_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to=apps.blog.models.custom_autor_upload_to, verbose_name='Imagen'),
        ),
    ]
