# Generated by Django 2.2.3 on 2019-08-19 02:59

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190818_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.custom_post_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=90, verbose_name='Titulo'),
        ),
    ]
